import {
  create,
  NAvatar,
  NBreadcrumb,
  NBreadcrumbItem,
  NButton,
  NCard,
  NCheckbox,
  NCheckboxGroup,
  NDataTable,
  NDatePicker,
  NDrawer,
  NDrawerContent,
  NDropdown,
  NForm, NFormItem,
  NGradientText,
  NIcon,
  NImage,
  NInput,
  NInputNumber,
  NLayout,
  NLayoutContent,
  NLayoutFooter,
  NLayoutHeader,
  NLayoutSider,
  NMenu,
  NModal,
  NRadio,
  NRadioButton,
  NRadioGroup,
  NSelect,
  NSpace,
  NStatistic,
  NSwitch,
  NTabPane,
  NTabs,
  NTime,
  NTree,
  NUpload
} from 'naive-ui'
const naive = create({
  components: [
    NButton,
    NForm, NFormItem,
    NInput,
    NGradientText,
    NIcon,
    NLayout,NLayoutSider,NLayoutContent,NLayoutFooter,NLayoutHeader,
    NMenu,
    NImage,
    NAvatar,
    NDropdown,
    NBreadcrumb,NBreadcrumbItem,
    NDataTable,
    NModal,
    NCard,
    NSelect,
    NCheckboxGroup,
    NCheckbox,
    NSpace,
    NTree,
    NInputNumber,
    NDatePicker,
    NUpload,
    NTabs,
    NTabPane,
    NTime,
    NDrawer,
    NDrawerContent,
    NRadioGroup,
    NRadio,
    NRadioButton,
    NSwitch,
    NStatistic
  ]
})

export default naive